name: auto test model
on: [push]
jobs:
  train-and-report:
    runs-on: ubuntu-latest
    container: docker://ghcr.io/iterative/cml:0-dvc2-base1
    steps:
      - uses: actions/checkout@v3
      - name: Train model
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          python src/data/process_data.py
          python src/model/train.py  # generate plot.png
          python src/model/test.py  # generate plot.png
          echo "##tamamlandı" >> report.md
          cml comment create report.md

